name: Deploy to EC2 remote server

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{secrets.SSH_PRIVATE_KEY_WOL}}
      - name: Clone or Pull repo
        run: 
          if [! -d "/home/ec2-user/temp-website"]; then
            git clone git@github.com:abbddullah/temp-website.git /home/ec2-user/temp-website
          else 
            cd /home/ec2-user/temp-website
            git pull origin main
          fi
