name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan your-instance-ip >> ~/.ssh/known_hosts

      - name: Deploy using lftp
        run: |
          lftp -u $FTP_USERNAME,$FTP_PASSWORD example.com -e "mirror -R -e . /path/on/server"
